.github/workflows/pull_request_template.md
README.md

This PR adds a PR description template and a tentative developmental checklist for further usage, also modified `README.md` to include naming convention resources and updated steps on how to run app locally

docs: add basic pr template

---

.github/pull_request_template.md
README.md
client/package-lock.json
client/package.json
client/src/App.js
client/src/components/Navbar.js
client/src/pages/About.js
client/src/pages/Account.js
client/src/pages/Categories.js
client/src/pages/Home.js
client/src/styles/navbar.css
package-lock.json
package.json

_Provide some context for your changes and add images wherever applicable_
[] Unit tests added where applicable
[] Does not introduce any breaking changes
[] Ran `Prettier`

feat: added page routes

---

client/package-lock.json
client/src/components/Navbar.js
client/src/styles/navbar.css

Added effect for nav bar.
[] Unit tests added where applicable
[] Does not introduce any breaking changes
[] Ran `Prettier`

Added hover graphics.

---

.github/pull_request_template.md
client/src/components/Navbar.js
client/src/components/NavbarItem.js
client/src/constants.js
client/src/pages/About.js
client/src/pages/Account.js
client/src/pages/Categories.js
client/src/styles/navbar.css

This PR introduces `constants.js` to eliminate hard-coded values within components and promote easier modification. Refactored `Navbar.js` to reflect this change. Also made a small modification to the PR desc. template. Also added `NavItem` to dynamically add nav tabs instead of repeat code.

feat: add constants

---

.gitignore
package-lock.json
package.json
server/index.js
server/models/User.js

This PR integrates MongoDB database access through `mongoose` and console logs some sample data from the cluster upon spinning the server up. You should have received some emails from MongoDB Atlas to join the team.
If all is well (which it probably won't even after completing the steps), you should see this:
It is my understanding that I need to supply you guys with unique username/password credentials and I also need your IP addresses so you guys can access the DB cluster locally...
1. Create a `.env` file in the root of the project and add the following content:
`MONGO_USERNAME="<YOUR_USERNAME>"`
`MONGO_PASSWORD="<YOUR_PASSWORD"`
This server server should fetch your credentials from this `.env` file and put it in the URI.
This would not work right away as I think I need your IP …

feat: integrate mongodb

---

client/src/components/Footer.js
client/src/pages/About.js
client/src/pages/Account.js
client/src/pages/Categories.js
client/src/pages/Home.js
client/src/styles/footer.css

Created a footer component that can go at the bottom of any page on the website. Can change the content of paragraphs later.
Here is an Image without the page being filled:
Made sure that it fills to the bottom when items are added. Like the Alabama Caregiver Connect Website.

feat: added footer component

---

client/src/components/CategoryBox.js
client/src/components/categories/CategoryBox.js
client/src/pages/Categories.js
client/src/styles/categories.css
client/src/styles/category-box.css

Added a basic Box to hold any categories we add to the website. right now it only has an image of an announcement image as a background but when we get a list of categories, I can replace the static code using the constants file.
Here is what it would look like with multiple boxes:

feat: Added Category Box

---

client/package-lock.json
client/package.json
client/src/components/Navbar.js
client/src/components/NavbarItem.js
client/src/constants.js
client/src/styles/dropdown.css
client/src/styles/navbar.css
package-lock.json
package.json

Added a drop down menu for the About and Account navbar items.

Added a dropdown menu to the About and Account navbar  items.

---

client/package-lock.json
client/src/App.js
client/src/app/store.js
client/src/components/users/userList.js
client/src/features/users/userSlice.js
client/src/features/users/userThunks.js
client/src/pages/Home.js
server/index.js

1. Addition of `fetchUser` and `fetchUsers` functions in `userThunks.js`. These functions fetch user data from the server.
2. Addition of `UserList` component in `userList.js` to display the fetched user data. 
3. Update of `server/index.js` to handle GET requests to `/users`. Fetches all users in the user collection in the MongoDb database. Also '/users/:userId' to find user by Id.

feat: added user data to redux store

---

Group Website/deliverables.html
Group Website/index.html
Group Website/presentations.html
Group Website/projectWebsite.code-workspace
Group Website/sourceCode.html
Group Website/style.css
Group Website/videos.html

Created all files needed for team website

Created Team Website

---

client/package-lock.json
client/src/pages/Account.js
client/src/styles/about.css
client/src/styles/account.css
client/src/styles/categories.css
client/src/styles/home.css

Added basic styling and setup with the Account page
Also made it where the starting height of the div in between the Navbar and Footer extends the Footer to the bottom. 
Soon will add functionality to only show specific users post on Account page. I can wait to merge before then but I thought I would go ahead and merge this.

feat: Basic styling and setup for Account page

---

docs/index.html

Updated my bio 
Left to do:
- Updated bios
- Look at IDE list
- Update Tasks (Maybe)
_Provide some context for your changes and add images wherever applicable_

Update my Bio

---

docs/index.html

Bio update

---

client/src/App.js
client/src/components/categories/CategoryTagBar.js
client/src/components/posts/Contribution.js
client/src/components/userInfo/UserImage.js
client/src/components/userInfo/UserInfoSmall.js
client/src/features/users/userSlice.js
client/src/pages/Profile.js
client/src/styles/category-tag-bar.css
client/src/styles/contribution.css

Added Profile page and routing so when you click on the user's image or name on their post, it routes them to the profile page. 
Updated Category page routing so when you click on a category on a post it takes you to that corresponding Category page.

feat: Added Profile page and Category page routing update

---

client/src/pages/Home.js
server/index.js

Changed the get for '/profile' to fetch directly from our database.

feat: updated '/profile' endpoint

---

client/src/App.js
client/src/pages/Account.js
client/src/pages/EditProfile.js
client/src/styles/account.css
client/src/styles/edit-profile.css
server/index.js

WIP: Edit page button functions and sends user to edit profile page, where user can change info.

feat:edit-profile

---

client/src/components/posts/SinglePost.js
client/src/components/userInfo/UserImage.js
client/src/components/userInfo/UserInfoSmall.js
client/src/pages/Account.js
client/src/pages/EditProfile.js
client/src/styles/edit-profile.css
client/src/styles/user-info-small.css
server/index.js
server/models/User.js

fixes and changes include:
- logged out users clicking on a post sends them to login page
- logged in user clicking on their own profile image on post will send them to account page
- cs styling for profile pictures on post overview to hover when mouse is over to show it is usable
- editing profile no longer makes post history disappear

feat:bug-fixes

---

docs/sourceCode.html
docs/videos.html

Added source code and video demo to team website

Added source code and video demo

---

client/src/components/posts/SinglePost.js
client/src/features/posts/postsSlice.js
client/src/features/posts/postsThunks.js
client/src/pages/EditPostPage.js
client/src/styles/single-post.css
server/controllers/postsController.js
server/routes/posts.js

Created a delete button on the SinglePostPage. Added a pop up to ask again whether they want to delete the post or not deleting the post will take them back to their account page and clicking no will hid the pop up page. Later on, I am going to fix up the pop up because I want it to fill the screen with a slightly dark, transparent background and then the message box in the middle.
Here are some images of the changes:

feat: Added Edit-Post page and functionality

---

client/src/pages/AddPostPage.js
client/src/pages/EditPostPage.js
client/src/styles/new-post-page.css

Updated Post Styling for add and update post

Updated Post Styling

---

client/src/App.js

Added a small prototype polling feature to update posts around every 30 to 60 seconds if there is a change in the store.
This will probably have to change at some point.

feat: Added a polling feature to update posts.

---

docs/deliverables.html
docs/index.html

Edited Documentation for sprint 2

Sprint 2 Documentation Edits

---

client/src/App.js
client/src/app/store.js
client/src/components/navbar/NavbarItem.js
client/src/features/users/userSlice.js
client/src/features/users/userThunks.js
client/src/index.js
client/src/pages/Account.js
client/src/pages/AccountSettings.js
client/src/pages/AddPostPage.test.js
client/src/pages/Admin.js
client/src/pages/EditProfile.js
client/src/pages/Home.js
docs/deliverables.html
docs/index.html
server/controllers/usersController.js
server/index.js

This PR introduces two test cases for the `AddPostForm` component. One tests if the fields render correctly, the other is supposed to test if the API is being called with the correct data once some fields are filled. Only the first one works. I don't know why the other one doesn't. WIP.

feat: add basic automated testing prototype

---

client/src/pages/Account.js
client/src/pages/Category.js
client/src/pages/Home.js
client/src/pages/Profile.js
client/src/styles/account.css
client/src/styles/category-box.css
client/src/styles/category.css
client/src/styles/home.css

Added sorting functionality where posts are displayed: Home, Account, Category and Profile. Also added search functionality for these pages. For the home page, you can search for specific people. For the other pages, you can search for specific post titles.
A video demonstrating these changes will be either here or on the groupme chat.
Also added a background for the category titles on the category boxes:

Sorting and Searching

---

.dockerignore
Dockerfile
client/.dockerignore
client/Dockerfile
client/package.json
client/src/components/navbar/NavbarItem.js
client/src/constants.js
client/src/features/users/userThunks.js
docker-compose.yml
package.json

Dockerizing Project for hosting

Dockerizing

---

docker-compose.yml

Docker Ports changed for hosting

Docker Ports changed for hosting

---

client/public/index.html

Change file type in index.html to <!DOCTYPE html>

Change file type in index.html

---

client/src/components/posts/Contribution.js
client/src/features/comments/commentsSlice.js
client/src/features/comments/commentsThunks.js
docs/deliverables.html
docs/index.html
docs/sourceCode.html
docs/style.css
server/controllers/postsController.js
server/index.js
server/routes/posts.js

- Fixed a bug where freshly added comments can not be edited in some cases.
- Add deleting comments (was in my stash)
- Add documentation
https://github.com/kevinleey/SeniorForum/assets/55768372/11c1e78e-a4f1-478e-b3b4-c91f7467a708

feat: fix edit commenting bug + restore delete comments

---

docs/videos.html

Added sprint 3 video to the videos tab on the website

Began documentation on Source Code page

---

server/controllers/postsController.js

Deletes the comments now. But the comment count in the post overview won't change. I don't know why.

fix: sometimes delete won't work

---

client/src/features/comments/commentsThunks.js
client/src/pages/EditPostPage.js

fixed profile picture not being updated on new comments

Added more to admin page, added profile pictures

---

docs/sourceCode.html

Documentation update for directory.

Documentation Update for directory
